Monster saves only display if monster has proficiency
open5e/open5e pull request #465
Opened 2024-02-23 23:07 UTC by christophermiles

Saving throws are now only listed when the monster has proficiency in the save (which the API signals by having `number|null` on the `strength_save` property

Aboleth saving throws on D&D Beyond:

<img width="1224" alt="Screenshot 2024-02-24 at 9 55 46 am" src="https://github.com/open5e/open5e/assets/1767439/8a1170c5-a18f-4d2a-992b-98afcea6fc09">

Updated saving throws on Open5E:

<img width="1069" alt="Screenshot 2024-02-24 at 9 58 01 am" src="https://github.com/open5e/open5e/assets/1767439/b97f359c-5e9b-49a0-b751-c30722f17d6b">

<img width="912" alt="Screenshot 2024-02-24 at 9 55 59 am" src="https://github.com/open5e/open5e/assets/1767439/9774bc77-5876-43ea-b58b-14cb89c29f7a">

2024-02-24 10:09 UTC, calumbell requested changes
This is looking great, exactly what we were looking for. Cheers for picking this up so quickly!

Just a couple minor changes before it is perfect:

1) If a monster has no saving throw proficiencies (ie. `monster/goblin`) it would be good if we completely hide the **Saving Throws** label. Probably should have thought of that when opening the issue, mae culpa. Can probably be solved using a `v-if` directive against the length of the saving throws array.

<img width="673" alt="screenshot from Open5e of the goblin statblock with an empty Saving Throws section" src="https://github.com/open5e/open5e/assets/47755775/01a8120a-b7ff-435b-9248-73160dbdb70c">

2) The saves are seperated by commas on the compact statblock, but period on the expanded one. The commas are what published statblocks generally use. Reckon we could replace those periods with commas? This can probably be done using Tailwind classes, something like `after:content-['.']` and `[&:not(:last-child)]:after:content-[',_']` iirc

Also, thanks for flagging the weird differences between the expanded and compact statblocks. I am planning to open an issue to collapse these into a single page with a toggle to change the style between expanded & compact. Might be a good one to pick up if you were looking for another project?

Thanks again for your contribution!

2024-02-24 10:59 UTC, christophermiles commented
Ah yep, makes total sense to hide the saving throw field completely if there are no saves!

I wondered why periods were used instead of commas. I assumed it was a stylistic decision as it seems to be used for other fields as well, and didn’t want to overstep the mark. But I think commas makes more sense.

Is there a reason why these punctuation marks are added as pseudo-content via CSS and not just output into the HTML?

2024-02-24 11:01 UTC, christophermiles commented
Also I think the idea of a compact-mode toggle is a good one, and not just to consolidate the code; the UX currently makes it hard to go back to the full stat block from the compact one

2024-02-24 14:41 UTC, calumbell commented
> Is there a reason why these punctuation marks are added as pseudo-content via CSS and not just output into the HTML?

Personal preference really.

I find that using it keeps the markdown neater and easier to read than, for example, conditionally rendered commas in span tags between each item. Functionally, the commas are styling, so it make sense to me to handle it with CSS. Just my two cents, if you have another solution and the markup looks good, then don't let me stop you!

2024-02-24 21:48 UTC, christophermiles commented
> > Is there a reason why these punctuation marks are added as pseudo-content via CSS and not just output into the HTML?
> 
> Personal preference really.
> 
> I find that using it keeps the markdown neater and easier to read than, for example, conditionally rendered commas in span tags between each item. Functionally, the commas are styling, so it make sense to me to handle it with CSS. Just my two cents, if you have another solution and the markup looks good, then don't let me stop you!

Nah that makes sense. There were other places where periods were used as delimiters; I’ll change them too for consistency.

2024-02-24 22:53 UTC, christophermiles commented on pages/monsters/[id].vue
> -        <li v-for="ability in abilites" :key="ability.name">
Fixed typo in this property name

2024-02-24 22:53 UTC, christophermiles commented on pages/monsters/[id].vue
> +        <li v-if="abilities.filter((a) => a.save).length">
Added filter

2024-02-24 22:53 UTC, christophermiles commented on pages/monsters/[id].vue
> +            class="after:content-[','] last:after:content-[]"
Used Tailwind's `last` function to remove comma on last item

2024-02-24 22:54 UTC, christophermiles commented on pages/monsters/[id].vue
> +            <span v-if="skill >= 0">+</span>{{ skill }}
Used same approach as for saving throws to simplify the skills loop

2024-02-24 22:54 UTC, christophermiles commented on pages/monsters/[id].vue
> +          class="before:content-['_']"
Noticed there was a spacing issue here

2024-02-24 22:54 UTC, christophermiles commented on pages/monsters/[id].vue
> +          :inline="true"
IDE highlighted an issue with the prop type here

2024-02-24 22:55 UTC, christophermiles commented on pages/monsters/compact/[id].vue
> +      <div v-if="getSaves.length">
Filtering for compact view

2024-02-24 22:56 UTC, christophermiles commented on pages/monsters/compact/[id].vue
> +          };
Used `map` here to simplify the code

2024-02-25 08:40 UTC, calumbell approved these changes
Looks good! Everything works as expected on my local machine. I'll go ahead and get this approved and merged. Thanks again for your contribution!

2024-02-25 08:41 UTC, merged