Pagination for top level list pages
open5e/open5e pull request #530
Opened 2024-07-12 15:51 UTC by Sturlen

Closes #508. This PR makes all list pages paginated, to avoid the long load times when fetching thousands of items for a page. Filtering and sorting pages will now all fetch new data from the server have also been switched to fetch only the required data, rather than being client side. All fetching logic is now handled by the <api-results-table> itself, to simplify and make data fetching consistent across all pages. The spell list for each class are unchanged as they are a separate issue.

Will need to run `npm install` as I've installed the `@vueuse/core` for it's debouncedRef function, which greatly simplifies input denouncing. Could look into just extracting the functionality we need but it would take some time.

This PR is a draft right now because debouncing the filter input, to avoid making a new request for each keypress, is still in progress. I've run into some issues with Vue reactivity and the debouncing not playing well together and am still debugging. There's a also some logging that needs to be cleaned up.

Let me know if you have any feedback or want any changes done.

2024-07-25 19:17 UTC, Sturlen commented
Waiting for https://github.com/open5e/open5e-api/pull/483 before it's ready to be pushed to beta.

2024-08-02 18:17 UTC, Sturlen commented
Had to remove tests that mocked internal page API usage, due to these being replaced with new ones. Proper tests for these pages should be done in a later PR.

Other tests that test page rendering are passing.

2024-08-03 18:52 UTC, eepMoody requested changes
This looks awesome overall, and I think it's going to make the v2 switch _sooooo_ much easier to manage! Couple pages seem to be not filtering to the right content, but otherwise this looks gtg to me!

Would like to see a merge from staging before we do a final approval, since there's new test actions that would run against it.

2024-08-03 18:52 UTC, eepMoody commented on pages/races/index.vue
> +    />
Currently this is returning a list of sections instead of a list of races. Does it need a filter like the other `sections` related items have?

2024-08-03 18:52 UTC, eepMoody commented on pages/running/index.vue
> +  parent__in: 'Rules',
This also seems to be returning a list of all sections instead of just the ones from the sidebar list

2024-08-03 19:12 UTC, eepMoody commented
Sorry, IDE confusion with the auto-created issue 😵‍💫

2024-08-03 21:52 UTC, Sturlen commented
Thanks for catching those oversights. Both have been corrected. Staging has been merged in and the AI code review seems to have run, though I don't see any result from it.

2024-08-07 16:58 UTC, calumbell commented
@Sturlen This looks great, amazing work! Seems to work more-or-less as expected on local, but I did notice a couple to problems during snagging:

1) Results on the `/conditions` page doesn't appear to respect source selection
2) When no results are returned on a page, the page number indicator reads *Page 1 of 0*. My instinct would be to hide this bit of text when no results are returned, or change this to *Page 0 of 0*

<img width="750" alt="Screenshot 2024-08-07 at 17 48 08" src="https://github.com/user-attachments/assets/1a869a5b-7d90-434b-8169-2bce3ecfcd63">

2024-08-14 13:35 UTC, calumbell approved these changes
Thanks for making those changes, everything looks good to me. Happy to go ahead an approve this.

This is going to improve load times on our top-level pages so, brilliant work!

2024-08-14 13:41 UTC, calumbell commented
@Sturlen Just a few final notes. Really little ones, I promise!

1) Merge conflict is probably due to bumping the Nuxt version last week. Merging from staging and running `npm i` should fix it.

2) You left a few `console.log()` debug statements in your code (`components/ApiResultsTable.vue`, `components/ApiTableNav.vue`, `composables/api.ts`, `/pages/magic-items/index.vue`, `pages/monsters/index.vue`)

2024-08-14 18:32 UTC, calumbell commented
Looks like PR validation is stuck. I'll close and reopen the PR to rerun it

2024-08-14 18:41 UTC, merged